### ISSUE TITLE
the sphinxcontrib.manpage extension does not declare if it is safe for parallel reading

### ISSUE THREAD

**Issue by jan-matejka** [tdi/sphinxcontrib-manpage#3]
WARNING: the sphinxcontrib.manpage extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit                                                           
WARNING: doing serial read

```
% sphinx-build --version
sphinx-build 2.0.1
```

**Comment by tdi** [comment]
#4 Fixes is
